### ISSUE TITLE
Making app responsive for varying screen sizes

### ISSUE THREAD

**Issue by jai-k-gohil** [afgprogrammer/Flutter-Complete-e-commerce#3]
No consistent app look and feel across various screens!

To reproduce issue

- Try testing app on varying devices in simulator.
<img width="449" alt="Screenshot 2020-01-02 at 6 28 27 PM" src="https://user-images.githubusercontent.com/25748472/71668233-13dbcf80-2d8e-11ea-8035-4193cf3a6bb9.png">

This is how it looks on Iphone 11 Pro Max.

**Comment by afgprogrammer** [comment]
This should not happen, because we set a default height value for SliverAppBar and for another part like the main category you have to apply some styles.
