### ISSUE TITLE
Categories going in infinite loop

### ISSUE THREAD

**Issue by Anirudhk07** [afgprogrammer/Flutter-Complete-e-commerce#5]
Main Category , Best Category , Other Category going to infinite loop

**Comment by afgprogrammer** [comment]
@Anirudhk07  ????

**Comment by Anirudhk07** [comment]
In the homepage the listview for Main Category , Best Category , Other Category going to infinite loop i.e. infinite number of cards are coming as we scroll

**Comment by afgprogrammer** [comment]
@Anirudhk07 
no no, they are not infinite, they should have a limitation of the item number. like 10 items on each list.
